### PR TITLE
updated URL to existing one, on F-Droid

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by rocboronat** [comment]
Hi @dym-sh ! I'm afraid I will add a note that I didn't publish it on F-Droid. Maybe someone did something to the APK and now it mines bitcoins :·) But thanks for the PR!

**Comment by ghost** [comment]
>  It is built and signed by F-Droid, and guaranteed to correspond to [this source tarball](https://f-droid.org/repo/net.rocboronat.android.wallpaper.npe_3_src.tar.gz). 

difference from latest tarball in github releases: default `build.xml` and `proguard-project.txt` filled with mostly "PUT YOUR CODE HERE" comments, which were probably required or added by f-droid.

so unless you afaraid f-droid itself one day will start adding crypto-miners to its builds, this note is probably not needed.

**Comment by rocboronat** [comment]
Thanks a lot for the explanation, @dym-sh! Didn't know how it work :·)

**Comment by ghost** [comment]
also, it was most likely added through scanning google-play store for OSS links

https://gitlab.com/fdroid/fdroiddata/-/commit/c07631d69816b543f6f0269a35846d16b7466217

**Comment by rocboronat** [comment]
Oh! That's madness! Incredible job :clap::clap::clap::clap::clap:

Thanks for the explanation! 😊

**Pull request merged**
